### ISSUE TITLE
On first run of new project i get error

### ISSUE THREAD

**Issue by espensgr** [undergroundwires/bump-everywhere#6]
I added this workflow too the project:
```
name: Changelog
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Bump version and release
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and release
        uses: undergroundwires/bump-everywhere@1.1.2
```

`Could not retrieve latest version. Version "404-tekst" is invalid (not in `major.minor.patch` format)`
And this is the top of the package.json file:
```
{
  "package_name": "Mustasj webproject builder",
  "version": "1.3.0",
  "private": true,
  "description": "Gulp modules for an awesome front-end build tool",
  }
```
